config/routes.rb
Rails.application.routes.draw do
	root to: 'pages#home'
	resources :tasks,  except:  [:index]
	
	get '/responses/new', to: 'responses#new'
	post '/responses/new', to: 'responses#create'
	
	get '/responses/newLastResponse', to: 'responses#newLastResponse'
	post '/responses/newLastResponse', to: 'responses#createLastResponse'
	
	get '/survey/bg', to: 'survey#bg'
	post '/survey/bg', to: 'survey#createBg'
	
	get '/survey/instructions', to: 'survey#instructions'
	post '/survey/proceedToThreads', to: 'survey#proceedToThreads'
	
	get '/survey/thread1', to: 'survey#thread1'
	post '/survey/thread1', to: 'survey#proceed1'
	
	get '/survey/thread2', to: 'survey#thread2'
	post '/survey/thread2', to: 'survey#proceed2'
	
	get '/survey/thread3', to: 'survey#thread3'
	post '/survey/thread3', to: 'survey#proceed3'
	
	get '/survey/thread4', to: 'survey#thread4'
	post '/survey/thread4', to: 'survey#proceed4'
	
	get '/survey/exit', to: 'survey#exit'
	post '/survey/exit', to: 'survey#proceedToThankyou'	
	
	get '/done', to: 'survey#thankyou'
	
	get 'testLoadBalancing', to: 'test#testLoadBalancing'
	get 'testSentenceHighlighting', to:'test#testSentenceHighlighting'
end

app/controllers/survey_controller.rb
class SurveyController < ApplicationController
	include AddResponse
	include FetchQuestions
	include ThreadHelpers
	MAX_RESPONSES = 3
	
	def bg
		# Keep track of session nbs
		unless checkSessionNb(0,true) then return end
		session[:completed] = false
		
		# Generate threads + initialize session for new user
		initializeSession
		
		# Initialize member fields
		fetchQuestions(["qtype = ?", :bg])
		@title = 'Background Questions'
		@formName = :backgroundQuestions
	end
	
	def createBg
		# Keep track of session nbs
		unless checkSessionNb(0,false) then return end
		updateSessionNb(1)
		
		answers = params[:backgroundQuestions].permit!.to_h
		userID = session.id
		addResponse('Background Questions', answers, userID)
		redirect_to survey_instructions_path
	end
	
	def instructions
		unless checkSessionNb(1,true) then return end
	end
	
	def proceedToThreads
		unless checkSessionNb(1,false) then return end
		updateSessionNb(2)
		redirect_to survey_thread1_path
	end
	
	def thread1
		unless checkSessionNb(2,true) then return end
		generateThread(1)
	end
	
	def proceed1
		# Keep track of session nbs
		unless checkSessionNb(2,false)then return end
		updateSessionNb(3)
		
		redirect_to survey_thread2_path
	end
	
	def thread2
		unless checkSessionNb(3,true) then return end
		
		generateThread(2)
	end
	
	def proceed2
		# Keep track of session nbs
		unless checkSessionNb(3,false) then return end
		updateSessionNb(4)
		
		redirect_to survey_thread3_path
	end
	
	def thread3
		unless checkSessionNb(4,true) then return end
		
		generateThread(3)
	end
	
	def proceed3
		# Keep track of session nbs
		unless checkSessionNb(4,false) then return end
		updateSessionNb(5)
		
		
		redirect_to survey_thread4_path
	end
	
	def thread4
		unless checkSessionNb(5,true) then return end
		
		generateThread(4)
	end
	
	def proceed4
		# Keep track of session nbs
		unless checkSessionNb(5,false) then return end
		updateSessionNb(6)
		
		
		redirect_to survey_exit_path
	end
	
	def exit
		unless checkSessionNb(6,true) then return end
		
		# Initialize member fields
		fetchQuestions(["qtype = ?", :eg])
		@title = 'Feedback'
		@formName = :backgroundQuestions
	end
	
	def proceedToThankyou
		unless checkSessionNb(6,false) then return end
		updateSessionNb(7)
		
		redirect_to done_path
	end
	
	def thankyou
		unless checkSessionNb(7,true) then return end
		deleteSessionNb()
		
		@sessionNb = session.id
	
	end
	
	private
	def generateThread(nb)
		# Get threadID
		if session[:completedPages].key? nb.to_s # If page is visited earlier, get cached threadID
			@threadID = session[:completedPages][nb.to_s]
		elsif session[:randomPage] == nb
			@threadID = Sentence.find(-1).thread_id
			session[:completedPages][nb.to_s] = @threadID
		else 
			@threadID = session[:threads].pop
			session[:completedPages][nb.to_s] = @threadID
		end
		
		@form = 'thread' + nb.to_s
		@user_id = session[:id]
		@sentences = getThreadSentenceMapping @threadID
		session[:toAnswer] += getSentenceIDs @threadID
		session[:toAnswer] &= getSentenceIDs @threadID # Remove duplicates
		nextPath = 'survey_thread' + nb.to_s + '_path'
		@nextPath =  eval("#{nextPath}")
		render :layout => false
	end
	
	def checkSessionNb(pageNb, isGet)
		if session.key? :page and not session[:completed]
			if session[:page] == pageNb then 
				return true
			else
				path = pageNbToPath(session[:page])
				redirect_to path
				return false
			end
		else
			if isGet and pageNb == 0 
				# If new user on the first page, return true so that calling method does not exit
				return true 
			else
				redirect_to pageNbToPath(0)
				return false
			end
		end
	end
	
	def pageNbToPath(pageNb)
		if pageNb == 0
			return survey_bg_path
		elsif pageNb == 1
			return survey_instructions_path
		elsif pageNb == 2
			return survey_thread1_path
		elsif pageNb == 3
			return survey_thread2_path
		elsif pageNb == 4
			return survey_thread3_path
		elsif pageNb == 5
			return survey_thread4_path
		elsif pageNb == 6
			return survey_exit_path
		end
	end
	
	def updateSessionNb(pageNb)
		session[:page] = pageNb
	end
	
	def deleteSessionNb
		session[:completed] = true
	end
	
	def initializeSession
		session[:threads] = generateThreads(MAX_RESPONSES) # The threads that this user will be assessing
		prng = Random.new
		session[:randomPage] = Random.rand(1..4) # Randomly decide which page is going to display the dummy question
		session[:page] = 0 # To keep track of completed pages and threads
		session[:answeredSentences] = [] # IDs of all sentences whose questions have already been answered
		session[:toAnswer] = [] # IDs of sentences whose questions should be answered so far to go to next page
		session[:completedPages] = {} # Links every page number to its respectiv thread ID
	end
end

app/helpers/survey_helper.rb
module SurveyHelper
end

app/views/survey/_general_form.html.haml
.container
	.modal-header
		%h1= @title
	= simple_form_for @formName, class: 'clearfix' do |f|
		.modal-body
			- @questions.each do |id,sentenceText|
				- isRequired = @questionRequirement[id]
				- isMultiple = false
				- if sentenceText.include? '||' # Question is a multiple choice question
					- isMultiple = true
					- choices = sentenceText.split(' || ')
					- sentenceText = choices.shift
					= f.input :"#{id}", :label=> "#{sentenceText}", :collection => choices, required: isRequired
				- elsif @questionType[id] == 'text'
					= f.input :"#{id}", :label=> "#{sentenceText}", required: isRequired, :as => "text"
				- else
					= f.input :"#{id}", :label=> "#{sentenceText}", required: isRequired
		.modal-footer
			= f.submit 'Next', class: 'btn btn-primary'

app/views/survey/_survey_form.html.haml
-url = 'https://stackoverflow.com/questions/' + @threadID
- page = Nokogiri::HTML(open(url))

-# Remove all StackOverFlow JavaScript
- nodes = []
- page.css('head')[0].children.each do |child|
	- if child.name == 'meta' or child.name == 'link' then nodes.push(child) end
- head = page.css('head')[0]
- head.inner_html = ''
- nodes.each do |node| head.add_child node end
- body = page.css('body')[0]
- body.children.each do |child|
	- if child.name == 'script' or child.name == 'noscript' then child.remove end

-# Add our stylesheets and JavaScript
- additions = stylesheet_link_tag    'application', media: 'all'
- additions += javascript_include_tag 'application'
- additions += csrf_meta_tags
- head.inner_html += additions
-#
- def removeIfExist(page, componentSpecifier)
	- multiple = false
	- if componentSpecifier[0] == '.' then multiple = true end
	- component = page.css(componentSpecifier)
	- if multiple 
		- unless component.empty?
			- component.each do |cmp| cmp.remove end
	- unless multiple
		- unless component.empty?
			- component[0].remove


-# Removing unnecessary components
-# removeIfExist(page, '#left-sidebar')
-# removeIfExist(page, '#sidebar')
- removeIfExist(page, '#js-gdpr-consent-banner')
- removeIfExist(page, '#dfp-tlb')
- removeIfExist(page, '#post-form')
- removeIfExist(page, '#tabs')
- removeIfExist(page, '#custom-header')
- removeIfExist(page, '#dfp-mlb') # Remove empty div space
- removeIfExist(page, '.comment-user')
- removeIfExist(page, '.post-signature')
- removeIfExist(page, '.pl8') # Remove 'Ask Question' button

-# Highlighting questions
- def searchArray(arr, key)
	- arr.each do |a|
		- if a.to_s == key.to_s then return true end
	- return false

- @sentences.each do |answerID, sentenceTexts|
	- sentenceTexts.each do |sentenceContainer|
		- sentence_id = sentenceContainer[0]
		- sentence_text = sentenceContainer[1]	
		- searchResult = searchArray(session[:answeredSentences], sentence_id)
		- if searchResult # Responses for this sentence have already been submitted
			- sentenceReplacement = '<mark style="background-color: grey">' + sentence_text + '</mark>'
		- else # Responses for this sentence have not been submitted yet
			- btn = link_to sentence_text, responses_new_path(:picked_sentence => { :sentence_id => sentence_id.to_s}), remote: true
			- sentenceReplacement = '<mark>' + btn + '</mark>'
		- highlightedAnswer = page.css('#' + answerID)[0].inner_html.gsub(sentence_text, sentenceReplacement)
		- page.css('#' + answerID)[0].inner_html = highlightedAnswer

-# Calculate the number of highlighted sentences that the user have to address to continue
- questionsLeft = session[:toAnswer] - session[:answeredSentences]
- questionsLeft = questionsLeft.count

-# Reuse right side bar for response form
- rightSideBar = page.css('#sidebar')[0]
- rightSideBar[:class] = 'left-sidebar--sticky-container js-sticky-leftnav'
- unless questionsLeft == 0
	- rightSideBar.inner_html = '<h1> Click on a highlighted sentence to get questions (' + questionsLeft.to_s + ' sentences left) </h1>'
- else
	- rightSideBar.inner_html = '<h1> All sentences are Answered. Click on "Next Thread" button on the left to continue </h1>'

-# Reuse left side bar for a navigation button
- leftSideBar = page.css('#left-sidebar')
- if leftSideBar.empty? then # Not a thread page, ignore it
- else
	-# Delete all divs inside the left side bar
	- leftSideBar = leftSideBar[0]
	- leftSideBar.children.each do |child| child.remove end
	-# Create new button and add it to the left side bar
	- btn = Nokogiri::XML::Node.new('div', page)
	- btn['class'] = 'left-sidebar--sticky-container js-sticky-leftnav btn btn-primary'
	- leftSideBar.add_child(btn)
	-# Fill button with the right HTML
	- if questionsLeft == 0
		- btn.inner_html = link_to 'Next Thread', @nextPath, method: :post, style: 'color: white'
	- else
		- btn.inner_html = 'Answer ' + questionsLeft.to_s + ' more sentences to proceed'

= html = page.to_html.html_safe

app/views/survey/_thread_form.html.haml
-url = 'https://stackoverflow.com/questions/' + @threadID.to_s
- page = Nokogiri::HTML(open(url))

-# Remove all StackOverFlow JavaScript
- nodes = []
- page.css('head')[0].children.each do |child|
	- if child.name == 'meta' or child.name == 'link' then nodes.push(child) end
- head = page.css('head')[0]
- head.inner_html = ''
- nodes.each do |node| head.add_child node end
- body = page.css('body')[0]
- body.children.each do |child|
	- if child.name == 'script' or child.name == 'noscript' then child.remove end

-# Add our stylesheets and JavaScript
- additions = stylesheet_link_tag    'application', media: 'all'
- additions += javascript_include_tag 'application'
- additions += csrf_meta_tags
- head.inner_html += additions

- def removeIfExist(page, componentSpecifier)
	- multiple = false
	- if componentSpecifier[0] == '.' then multiple = true end
	- component = page.css(componentSpecifier)
	- if multiple 
		- unless component.empty?
			- component.each do |cmp| cmp.remove end
	- unless multiple
		- unless component.empty?
			- component[0].remove


-# Removing unnecessary components
- removeIfExist(page, '#js-gdpr-consent-banner')
- removeIfExist(page, '#dfp-tlb')
- removeIfExist(page, '#post-form')
- removeIfExist(page, '#tabs')
- removeIfExist(page, '#custom-header')
- removeIfExist(page, '#dfp-mlb') # Remove empty div space
- removeIfExist(page, '.comment-user')
- removeIfExist(page, '.post-signature')
- removeIfExist(page, '.pl8') # Remove 'Ask Question' button

-# Highlighting questions
- def searchArray(arr, key)
	- arr.each do |a|
		- if a.to_s == key.to_s then return true end
	- return false

- logger.debug '---------------debug----------------'
- @sentences.each do |answerID, sentenceTexts|
	- if answerID == '-1' then next end # Ignore dummy sentences
	- sentenceTexts.each do |sentenceContainer|
		- sentence_id = sentenceContainer[0]
		- sentence_text = sentenceContainer[1]
		- searchResult = searchArray(session[:answeredSentences], sentence_id)
		- if searchResult # Responses for this sentence have already been submitted
			- sentenceReplacement = '<mark style="background-color: grey">' + sentence_text + '</mark>'
		- else # Responses for this sentence have not been submitted yetbefore tags inside the target sentence
			- logger.debug sentence_text
			- logger.debug page.css('#' + answerID)[0].inner_html.include? "/>= 9.5 and they only care about top-level elements being merged without duplicate keys, then it's as easy as using the || operator:"
			- btn = link_to sentence_text.html_safe, responses_new_path(:picked_sentence => { :sentence_id => sentence_id.to_s}), remote: true
			- sentenceReplacement = '<mark>' + btn + '</mark>'
		- highlightedAnswer = page.css('#' + answerID)[0].inner_html.gsub(sentence_text, sentenceReplacement)
		- page.css('#' + answerID)[0].inner_html = highlightedAnswer
- logger.debug '------------end of debug-------------'

-# Calculate the number of highlighted sentences that the user have to address to continue
- questionsLeft = session[:toAnswer] - session[:answeredSentences]
- questionsLeft = questionsLeft.count

-# Reuse right side bar for response form
- rightSideBar = page.css('#sidebar')[0]
- rightSideBar[:class] = 'left-sidebar--sticky-container js-sticky-leftnav'
- if questionsLeft == 1
	- rightSideBar.inner_html = '<h1> One last question about the thread. Click on the "Thread Question" button on the left to continue </h1>'
- elsif questionsLeft == 0
	- rightSideBar.inner_html = '<h1> All sentences are Answered. Click on "Next Thread" button on the left to continue </h1>'
- else
	- rightSideBar.inner_html = '<h1> Click on a highlighted sentence to get questions (' + (questionsLeft - 1).to_s + ' sentences left) </h1>'

-# Change width ratio between main div and right sidebar (now used as form)
- rightSideBar[:style] = 'width: 400px;'
- page.css('#mainbar')[0][:style] = 'width: calc(100% - 400px - 24px);'

-# Reuse left side bar for a navigation button
- leftSideBar = page.css('#left-sidebar')
- if leftSideBar.empty? then # Not a thread page, ignore it
- else
	-# Delete all divs inside the left side bar
	- leftSideBar = leftSideBar[0]
	- leftSideBar.children.each do |child| child.remove end
	-# Create new button and add it to the left side bar
	- btn = Nokogiri::XML::Node.new('div', page)
	- btn['class'] = 'left-sidebar--sticky-container js-sticky-leftnav'
	- leftSideBar.add_child(btn)
	-# Fill button with the right HTML
	- if questionsLeft == 0
		- btn.inner_html = link_to 'Next Thread', @nextPath, method: :post, style: 'color: white', class: 'btn btn-primary'
	- elsif questionsLeft == 1
		- btn.inner_html = link_to 'Thread Question', responses_newLastResponse_path(:picked_thread => { :thread_id => @threadID.to_s}), style: 'color: white', class: 'btn btn-primary', remote: true
	- else
		- btn.inner_html = 'Answer ' + (questionsLeft - 1).to_s + ' more sentences to proceed'
		- btn[:class] = 'btn btn-primary'

= html = page.to_html.html_safe
#modal.modal.fade

-# Debugging
	= btn.inner_html = link_to 'Next Thread', @nextPath, method: :post, style: 'color: white', class: 'btn btn-primary'
	%table.table.table-hover.table-bordered
		%thead
			%tr
				%th Variable
				%th Value
		%tbody
			%tr
				%td Random Page: 
				%td= session[:randomPage]
			%tr
				%td Threads: 
				%td= session[:threads]
			%tr
				%td Thread ID: 
				%td= @threadID
			%tr
				%td Sentences that should be answered:
				%td= session[:toAnswer]
			%tr
				%td Answered questions
				%td= session[:answeredSentences]

app/views/survey/bg.html.haml
= render partial: 'general_form'

app/views/survey/exit.html.haml
= render partial: 'general_form'

app/views/survey/instructions.html.haml
.container
	%h1 Instructions Page
	= link_to "Let's Go!", survey_proceedToThreads_path, method: :post, class: 'btn btn-primary'

app/views/survey/testLoadBalancing.html.haml
.container
	%h1= @threadIDs

app/views/survey/thankyou.html.haml
.container
	%h1 Thank you for filling the form. Your token is:
	%h1= @sessionNb
	%h2 Please save this token before closing the browser tab since you will not be able to view it again

app/views/survey/thread1.html.haml
= render partial: 'thread_form'

app/views/survey/thread2.html.haml
= render partial: 'thread_form'

app/views/survey/thread3.html.haml
= render partial: 'thread_form'

app/views/survey/thread4.html.haml
= render partial: 'thread_form'