config/routes.rb
Rails.application.routes.draw do
	root to: 'pages#home'
	resources :tasks,  except:  [:index]
	
	get '/responses/new', to: 'responses#new'
	post '/responses/new', to: 'responses#create'
	
	get '/responses/newLastResponse', to: 'responses#newLastResponse'
	post '/responses/newLastResponse', to: 'responses#createLastResponse'
	
	get '/survey/bg', to: 'survey#bg'
	post '/survey/bg', to: 'survey#createBg'
	
	get '/survey/instructions', to: 'survey#instructions'
	post '/survey/proceedToThreads', to: 'survey#proceedToThreads'
	
	get '/survey/thread1', to: 'survey#thread1'
	post '/survey/thread1', to: 'survey#proceed1'
	
	get '/survey/thread2', to: 'survey#thread2'
	post '/survey/thread2', to: 'survey#proceed2'
	
	get '/survey/thread3', to: 'survey#thread3'
	post '/survey/thread3', to: 'survey#proceed3'
	
	get '/survey/thread4', to: 'survey#thread4'
	post '/survey/thread4', to: 'survey#proceed4'
	
	get '/survey/exit', to: 'survey#exit'
	post '/survey/exit', to: 'survey#proceedToThankyou'	
	
	get '/done', to: 'survey#thankyou'
	
	get 'testLoadBalancing', to: 'test#testLoadBalancing'
	get 'testSentenceHighlighting', to:'test#testSentenceHighlighting'
end

app/views/pages/home.html.haml
.container
	= link_to 'Take Survey!', survey_bg_path, class: 'btn btn-primary'
-#	= link_to 'New Task', new_task_path, class: 'btn btn-primary', remote: true
#modal.modal.fade
-#
	.container
		- if @tasks.empty?
			%span.text-warning There are not tasks
		- else
			%table.table.table-hover.table-bordered
				%thread
					%tr
						%th Title
						%th Created at
						%th Completed
					%tbody
						- @tasks.each do |task|
							%tr
								%td
									%strong= task.title
								%td.text-info= task.created_at
								%td.text-success= task.completed
	#modal.modal.fade